# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/lutyjj/esp32-streamline/mainline/docs/bridge-openapi.json

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class ClientSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    batches_sent: Annotated[int, Field(ge=0, title="Batches Sent")]
    bytes_sent: Annotated[int, Field(ge=0, title="Bytes Sent")]
    chunks_sent: Annotated[int, Field(ge=0, title="Chunks Sent")]
    connected_at: Annotated[float, Field(title="Connected At")]
    id: Annotated[int, Field(ge=1, title="Id")]
    last_write_at: Annotated[float | None, Field(title="Last Write At")]
    path: Annotated[str, Field(title="Path")]
    queue_depth: Annotated[int, Field(ge=0, title="Queue Depth")]
    queue_drops: Annotated[int, Field(ge=0, title="Queue Drops")]
    remote_addr: Annotated[str, Field(title="Remote Addr")]


class DeleteRecordingResult(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    deleted: Annotated[str, Field(title="Deleted")]


class DownloadTicket(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    expires_in_seconds: Annotated[int, Field(gt=0, title="Expires In Seconds")]
    url: Annotated[str, Field(title="Url")]


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    code: Annotated[str, Field(title="Code")]
    message: Annotated[str, Field(title="Message")]


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    error: ErrorDetail


class LevelSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    peak_left: Annotated[int, Field(ge=0, le=32768, title="Peak Left")]
    peak_right: Annotated[int, Field(ge=0, le=32768, title="Peak Right")]
    rms_left: Annotated[int, Field(ge=0, le=32768, title="Rms Left")]
    rms_right: Annotated[int, Field(ge=0, le=32768, title="Rms Right")]


class RecordingFormat(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    bits_per_sample: Annotated[int, Field(gt=0, title="Bits Per Sample")]
    bytes_per_second: Annotated[int, Field(gt=0, title="Bytes Per Second")]
    channels: Annotated[int, Field(gt=0, title="Channels")]
    codec: Annotated[Literal["pcm_s16le"], Field(title="Codec")]
    container: Annotated[Literal["wav"], Field(title="Container")]
    sample_rate: Annotated[int, Field(gt=0, title="Sample Rate")]


class RecordingLimits(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    max_duration_seconds: Annotated[int, Field(gt=0, title="Max Duration Seconds")]
    max_gap_seconds: Annotated[int, Field(gt=0, title="Max Gap Seconds")]
    max_title_chars: Annotated[int, Field(gt=0, title="Max Title Chars")]
    min_free_bytes: Annotated[int, Field(ge=0, title="Min Free Bytes")]
    queue_chunks: Annotated[int, Field(gt=0, title="Queue Chunks")]


class RecordingSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    audio_started_at: Annotated[str | None, Field(title="Audio Started At")]
    bytes: Annotated[int, Field(ge=0, title="Bytes")]
    created_at: Annotated[str, Field(title="Created At")]
    duplicate_packets: Annotated[int, Field(ge=0, title="Duplicate Packets")]
    duration_seconds: Annotated[float, Field(ge=0.0, title="Duration Seconds")]
    error: Annotated[str | None, Field(title="Error")]
    file_name: Annotated[str | None, Field(title="File Name")]
    finished_at: Annotated[str | None, Field(title="Finished At")]
    frames: Annotated[int, Field(ge=0, title="Frames")]
    gap_packets: Annotated[int, Field(ge=0, title="Gap Packets")]
    id: Annotated[str, Field(title="Id")]
    source: Annotated[str, Field(title="Source")]
    state: Annotated[
        Literal["waiting-for-audio", "recording", "finalizing", "complete", "interrupted", "empty"],
        Field(title="State"),
    ]
    title: Annotated[str, Field(title="Title")]


class RecordingStorage(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    free_bytes: Annotated[int, Field(ge=0, title="Free Bytes")]


class EvictionIdleSeconds(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, title="Eviction Idle Seconds")]


class SourceLifecycle(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    dynamic: Annotated[bool, Field(title="Dynamic")]
    eviction_idle_seconds: Annotated[
        EvictionIdleSeconds | None, Field(title="Eviction Idle Seconds")
    ] = None
    http_clients: Annotated[int, Field(ge=0, title="Http Clients")]
    idle_seconds: Annotated[float, Field(ge=0.0, title="Idle Seconds")]
    peer_ip: Annotated[str, Field(title="Peer Ip")]
    recording_sessions: Annotated[int, Field(ge=0, title="Recording Sessions")]
    state: Annotated[
        Literal["pending", "connected", "http-selected", "allowlisted", "disconnected"],
        Field(title="State"),
    ]
    transport: Annotated[Literal["cleartext", "tls-psk"], Field(title="Transport")]


class HighestSeq(RootModel[int]):
    root: Annotated[int, Field(ge=0, title="Highest Seq")]


class LastSeq(RootModel[int]):
    root: Annotated[int, Field(ge=0, title="Last Seq")]


class PacketFrames(RootModel[int]):
    root: Annotated[int, Field(ge=1, title="Packet Frames")]


class PlayoutSeq(RootModel[int]):
    root: Annotated[int, Field(ge=0, title="Playout Seq")]


class SourceSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    buffer_ready_at: Annotated[float | None, Field(title="Buffer Ready At")]
    buffered_packets: Annotated[int, Field(ge=0, title="Buffered Packets")]
    bytes: Annotated[int, Field(ge=0, title="Bytes")]
    client_buffer_chunks: Annotated[int, Field(ge=1, title="Client Buffer Chunks")]
    client_queue_drops: Annotated[int, Field(ge=0, title="Client Queue Drops")]
    client_streams: Annotated[list[ClientSnapshot], Field(title="Client Streams")]
    clients: Annotated[int, Field(ge=0, title="Clients")]
    concealed: Annotated[int, Field(ge=0, title="Concealed")]
    duplicate: Annotated[int, Field(ge=0, title="Duplicate")]
    frames: Annotated[int, Field(ge=0, title="Frames")]
    highest_seq: Annotated[HighestSeq | None, Field(title="Highest Seq")] = None
    last_packet_at: Annotated[float | None, Field(title="Last Packet At")]
    last_playout_at: Annotated[float | None, Field(title="Last Playout At")]
    last_seq: Annotated[LastSeq | None, Field(title="Last Seq")] = None
    late: Annotated[int, Field(ge=0, title="Late")]
    levels: LevelSnapshot
    lifecycle: SourceLifecycle
    lost: Annotated[int, Field(ge=0, title="Lost")]
    max_outage_silence_packets: Annotated[int, Field(ge=1, title="Max Outage Silence Packets")]
    packet_frames: Annotated[PacketFrames | None, Field(title="Packet Frames")] = None
    packets: Annotated[int, Field(ge=0, title="Packets")]
    played_frames: Annotated[int, Field(ge=0, title="Played Frames")]
    playout_buffer_packets: Annotated[int, Field(ge=1, title="Playout Buffer Packets")]
    playout_seq: Annotated[PlayoutSeq | None, Field(title="Playout Seq")] = None
    rate: Annotated[int, Field(gt=0, title="Rate")]
    reordered: Annotated[int, Field(ge=0, title="Reordered")]
    slow_clients: Annotated[int, Field(ge=0, title="Slow Clients")]
    started_at: Annotated[float, Field(title="Started At")]
    tcp_connections: Annotated[int, Field(ge=0, title="Tcp Connections")]
    tcp_disconnects: Annotated[int, Field(ge=0, title="Tcp Disconnects")]
    tcp_errors: Annotated[int, Field(ge=0, title="Tcp Errors")]
    underruns: Annotated[int, Field(ge=0, title="Underruns")]
    uptime_seconds: Annotated[float, Field(ge=0.0, title="Uptime Seconds")]


class StartRecordingRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    source: Annotated[str, Field(title="Source")]
    title: Annotated[str, Field(max_length=80, min_length=1, title="Title")]


class TransportKeyDeleteResult(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    deleted: Annotated[str, Field(title="Deleted")]


class TransportKeyRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    psk: Annotated[str, Field(pattern="^[0-9a-f]{64}$", title="Psk")]


class TransportKeyResult(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    key_id: Annotated[str, Field(title="Key Id")]


class TransportModeRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    mode: Annotated[Literal["cleartext", "tls-psk"], Field(title="Mode")]


class TransportSnapshot(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    auth_failures: Annotated[int, Field(ge=0, title="Auth Failures")]
    auth_successes: Annotated[int, Field(ge=0, title="Auth Successes")]
    configurable: Annotated[bool, Field(title="Configurable")]
    contract_version: Annotated[Literal[1], Field(title="Contract Version")]
    key_ids: Annotated[list[str], Field(title="Key Ids")]
    mode: Annotated[Literal["cleartext", "tls-psk"], Field(title="Mode")]
    port: Annotated[int, Field(ge=1, le=65535, title="Port")]


class UnlockResult(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: Annotated[Literal[True], Field(title="Ok")]


class ValidationError(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ctx: Annotated[dict[str, Any] | None, Field(title="Context")] = None
    input: Annotated[Any | None, Field(title="Input")] = None
    loc: Annotated[list[str | int], Field(title="Location")]
    msg: Annotated[str, Field(title="Message")]
    type: Annotated[str, Field(title="Error Type")]


class BridgeStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    api_token_configured: Annotated[bool, Field(title="Api Token Configured")]
    bridge_version: Annotated[str, Field(title="Bridge Version")]
    sources: Annotated[dict[str, SourceSnapshot], Field(title="Sources")]
    transport: TransportSnapshot


class HTTPValidationError(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    detail: Annotated[list[ValidationError] | None, Field(title="Detail")] = None


class RecordingCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    enabled: Annotated[bool, Field(title="Enabled")]
    format: RecordingFormat
    limits: RecordingLimits


class RecordingList(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active: Annotated[list[RecordingSnapshot], Field(title="Active")]
    saved: Annotated[list[RecordingSnapshot], Field(title="Saved")]
    storage: RecordingStorage


class RecordingResult(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    recording: RecordingSnapshot
