# generated by datamodel-codegen:
#   filename:  device-openapi.json

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Ack(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ok: bool | None = None
    rebooting: bool | None = None
    started: bool | None = None


class ActiveAudioProfileRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    profile_id: Annotated[
        str | None, Field(description="Empty returns to custom audio settings.")
    ] = None


class AdminKeySettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    admin_secret: Annotated[
        str,
        Field(
            description="Generated 48-character lowercase-hex admin key.",
            max_length=48,
            min_length=48,
            pattern="^[0-9a-f]{48}$",
        ),
    ]


class AnalogPassthroughCapability(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    label: str
    output_line: Annotated[int, Field(ge=0)]


class AnalogPassthroughCapabilityStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    label: str
    output_line: Annotated[int, Field(ge=0)]


class AnalogPassthroughSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    enabled: bool


class AnalogPassthroughStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active: bool
    enabled: bool
    fault: str | None = None


class AudioProfilesSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    catalog: Annotated[str, Field(description="JSON-encoded `AudioProfileCatalog`.")]


class AudioSettings(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_attenuation_db: Annotated[int, Field(ge=0)]
    input_gain: Annotated[int, Field(ge=0)]
    input_line: Annotated[
        int,
        Field(description="Selected input, one of the resolved board's advertised lines.", ge=0),
    ]


class AudioSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_attenuation_db: Annotated[int, Field(ge=0)]
    input_gain: Annotated[int, Field(ge=0)]
    input_line: Annotated[int, Field(ge=0)]


class AudioStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_attenuation_db: Annotated[int, Field(ge=0)]
    bits_per_sample: Annotated[int, Field(ge=0)]
    channels: Annotated[int, Field(ge=0)]
    input_gain: Annotated[int, Field(ge=0)]
    input_line: Annotated[int, Field(ge=0)]
    sample_rate: Annotated[int, Field(ge=0)]


class AutoUpdateScheduleRequest(RootModel[Literal["disabled", "daily", "weekly"]]):
    root: Literal["disabled", "daily", "weekly"]


class BoardSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    board_id: str | None = None
    descriptor: Annotated[
        str | None,
        Field(
            description="JSON-encoded descriptor, capped at 3072 UTF-8 bytes by the device.",
            max_length=3072,
        ),
    ] = None


class BootLog(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    boot: Annotated[
        int,
        Field(
            description="Identifies the run of the firmware these lines came from. A poller\ncompares it to tell more lines from a restart that began counting\nagain, which sequence numbers alone cannot express.",
            ge=0,
        ),
    ]
    dropped: Annotated[
        int,
        Field(
            description="Lines this boot produced that the buffer has already discarded. A\nnon-zero count means `text` starts later than the boot did.",
            ge=0,
        ),
    ]
    first_sequence: Annotated[
        int,
        Field(
            description="Position of the first line within the boot, counted from zero. Each\nfollowing line is one higher.",
            ge=0,
        ),
    ]
    text: Annotated[str, Field(description="The held lines, oldest first, separated by newlines.")]


class ButtonAction(
    RootModel[
        Literal[
            "none",
            "toggle_stream",
            "cycle_input",
            "gain_up",
            "gain_down",
            "attenuation_up",
            "attenuation_down",
            "restart",
            "factory_reset",
        ]
    ]
):
    root: Annotated[
        Literal[
            "none",
            "toggle_stream",
            "cycle_input",
            "gain_up",
            "gain_down",
            "attenuation_up",
            "attenuation_down",
            "restart",
            "factory_reset",
        ],
        Field(description="The action assigned to a single board button, fired on a simple press."),
    ]


class ButtonActionStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    action: ButtonAction
    id: str


class ButtonCapabilityStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_low: bool
    default_action: ButtonAction
    gpio: Annotated[int, Field(ge=0)]
    id: str
    label: str


class ButtonSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    action: ButtonAction
    id: str


class CheckStatus(RootModel[Literal["ok", "warn", "fail"]]):
    root: Annotated[
        Literal["ok", "warn", "fail"],
        Field(description="The outcome of one check, independent of how much it matters."),
    ]


class CodecSpec(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    driver: str
    i2c_address: Annotated[int, Field(description="7-bit I2C address the codec answers on.", ge=0)]


class CodecStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    driver: str
    i2c_address: Annotated[int, Field(ge=0)]


class CoredumpResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    present: Annotated[
        bool, Field(description="Whether the partition holds a valid dump from an earlier panic.")
    ]
    size_bytes: Annotated[
        int,
        Field(description="Size of the stored ELF image in bytes; `0` when none is stored.", ge=0),
    ]


class DiagnosticsStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    last_fallback: str
    last_ota: str
    reset_reason: str


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    error: str


class FirmwareSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    auto_update_schedule: AutoUpdateScheduleRequest


class HeapStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    free_bytes: Annotated[int, Field(ge=0)]
    largest_free_block_bytes: Annotated[int, Field(ge=0)]
    minimum_free_bytes: Annotated[int, Field(ge=0)]
    total_bytes: Annotated[int, Field(ge=0)]


class I2cPins(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    scl: Annotated[int, Field(ge=0)]
    sda: Annotated[int, Field(ge=0)]


class I2cPinsStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    scl: Annotated[int, Field(ge=0)]
    sda: Annotated[int, Field(ge=0)]


class I2sPins(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    bclk: Annotated[int, Field(ge=0)]
    din: Annotated[int, Field(ge=0)]
    mclk: Annotated[int, Field(ge=0)]
    ws: Annotated[int, Field(ge=0)]


class I2sPinsStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    bclk: Annotated[int, Field(ge=0)]
    din: Annotated[int, Field(ge=0)]
    mclk: Annotated[int, Field(ge=0)]
    ws: Annotated[int, Field(ge=0)]


class IndicatorStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    available: bool
    state: str


class InputLineStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    label: str
    line: Annotated[int, Field(ge=0)]


class InputOption(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    label: str
    line: Annotated[int, Field(ge=0)]


class LedRole(RootModel[Literal["off", "on", "status"]]):
    root: Annotated[
        Literal["off", "on", "status"],
        Field(description="The behavior assigned to a single board LED."),
    ]


class LedRoleStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str
    role: LedRole


class LedSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    id: str
    role: LedRole


class LogsResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    current: BootLog
    previous: BootLog | None = None


class MetricsStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    bytes: Annotated[int, Field(ge=0)]
    clip_threshold_abs: Annotated[int, Field(ge=0)]
    clipped_samples_total: Annotated[int, Field(ge=0)]
    longest_send_stall_ms: Annotated[int, Field(ge=0)]
    network_errors_total: Annotated[int, Field(ge=0)]
    noise_floor: Annotated[int, Field(ge=0)]
    packets: Annotated[int, Field(ge=0)]
    peak_abs_left: Annotated[int, Field(ge=0)]
    peak_abs_right: Annotated[int, Field(ge=0)]
    playing: bool
    queue_depth: Annotated[int, Field(ge=0)]
    queue_drops_total: Annotated[int, Field(ge=0)]
    read_errors: Annotated[int, Field(ge=0)]
    reconnects_total: Annotated[int, Field(ge=0)]
    rms_left: Annotated[int, Field(ge=0)]
    rms_right: Annotated[int, Field(ge=0)]
    send_stalls_total: Annotated[int, Field(ge=0)]
    sequence: Annotated[int, Field(ge=0)]
    short_reads: Annotated[int, Field(ge=0)]
    stale_drops_total: Annotated[int, Field(ge=0)]
    tls_handshake_failures_total: Annotated[int, Field(ge=0)]


class NameSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    name: Annotated[str | None, Field(max_length=32)] = None


class NvsStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    available_entries: Annotated[int, Field(ge=0)]
    total_entries: Annotated[int, Field(ge=0)]
    used_entries: Annotated[int, Field(ge=0)]


class OtaStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    busy: bool
    bytes_total: Annotated[int, Field(ge=0)]
    bytes_written: Annotated[int, Field(ge=0)]
    latest_version: str
    message: str
    phase: str
    rollback_available: bool
    rollback_version: str
    signed_updates: Annotated[
        bool,
        Field(
            description="Whether this firmware rejects an over-the-air image that is not signed by\nthe vendor key it trusts. Always true on a signed release build; false on\nan unsigned self-build."
        ),
    ]


class OtaUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    sha256: Annotated[str | None, Field(pattern="^[0-9A-Fa-f]{64}$")] = None
    url: Annotated[
        str | None,
        Field(
            description="HTTP(S) download URL. Query parameters are preserved; userinfo and\nfragments are rejected.",
            pattern="^https?://[^/?#@\\s]+(?:[/?][^#\\s]*)?$",
        ),
    ] = None


class PinMap(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    i2c: I2cPins
    i2s: I2sPins


class PinMapStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    i2c: I2cPinsStatus
    i2s: I2sPinsStatus


class SetupNetworkResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    password: str
    ssid: str


class Severity(RootModel[Literal["ok", "info", "blocking"]]):
    root: Annotated[
        Literal["ok", "info", "blocking"],
        Field(
            description="How much a check's outcome matters to the user journey. A report's overall\n[`HealthReport::status`] is the worst severity across its checks."
        ),
    ]


class StreamControlStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    enabled: bool


class StreamRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    enabled: bool


class SystemStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    heap: HeapStatus
    nvs: NvsStatus
    task_count: Annotated[int, Field(ge=0)]
    uptime_seconds: Annotated[int, Field(ge=0)]


class TargetSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    target_host: Annotated[
        str | None,
        Field(
            description="Hostname or IP without a scheme, port, or path. Empty clears the target.",
            pattern="^[^:/]*$",
        ),
    ] = None
    target_port: Annotated[int | None, Field(ge=1)] = None


class TargetStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    target_host: str
    target_port: Annotated[int, Field(ge=0)]
    transport: str


class TransportKeyResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    contract_version: Annotated[int, Field(ge=0)]
    key_id: str
    psk: Annotated[
        str,
        Field(
            description="Shown once. The device never returns this PSK through a read endpoint.",
            pattern="^[0-9a-f]{64}$",
        ),
    ]


class TransportMode(RootModel[Literal["cleartext", "tls-psk"]]):
    root: Literal["cleartext", "tls-psk"]


class TransportSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    contract_version: Annotated[int, Field(ge=0)]
    mode: TransportMode


class TransportStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_key_id: str | None = None
    contract_version: Annotated[int, Field(ge=0)]
    mode: TransportMode
    pending_key_id: str | None = None
    pending_verified: bool
    rollback_key_id: str | None = None


class WifiSettingsRequest(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    admin_secret: Annotated[
        str | None,
        Field(
            description="Generated 48-character lowercase-hex admin key. Empty preserves the\nstored key.",
            pattern="^$|^[0-9a-f]{48}$",
        ),
    ] = None
    password: Annotated[
        str | None, Field(description="Wi-Fi password. Empty preserves the stored password.")
    ] = None
    ssid: Annotated[
        str, Field(description="Wi-Fi network name. Empty names are rejected.", min_length=1)
    ]
    target_host: Annotated[
        str | None,
        Field(
            description="Optional bridge host set during first commissioning.", pattern="^[^:/]*$"
        ),
    ] = None
    target_port: Annotated[int | None, Field(ge=1)] = None


class WifiStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    ap_ip: str
    hostname: str
    rssi: int
    ssid: str
    sta_ip: str
    status: str


class AudioProfile(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    audio: AudioSettings
    id: Annotated[str, Field(max_length=32, pattern="^[a-z0-9][a-z0-9-]*$")]
    name: Annotated[str, Field(max_length=32)]


class AudioProfileCatalog(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_profile_id: str | None = None
    board_id: str
    profiles: Annotated[list[AudioProfile], Field(max_length=8)]
    schema_version: Annotated[int, Field(ge=0)]


class Button(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_low: Annotated[
        bool | None,
        Field(
            description="`true` when the GPIO reads low while the button is held. The firmware\nenables the matching internal pull where the pin has one; input-only\npins (GPIO 34–39) rely on the board's own resistor."
        ),
    ] = None
    default_action: Annotated[
        ButtonAction | None,
        Field(
            description="Action fired until the user assigns another, so a board author can ship\nuseful presses while leaving spare buttons inert."
        ),
    ] = None
    gpio: Annotated[int, Field(ge=0)]
    id: Annotated[
        str,
        Field(
            description="Stable id, unique within the board, used to address the button in\nsettings."
        ),
    ]
    label: Annotated[
        str, Field(description="Human-readable name the console shows for this button.")
    ]


class ConfigResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_attenuation_db: Annotated[int, Field(ge=0)]
    analog_passthrough_enabled: bool
    auto_update_schedule: AutoUpdateScheduleRequest
    button_actions: Annotated[
        list[ButtonActionStatus],
        Field(description="The effective action of every board button, in descriptor order."),
    ]
    config_source: str
    device_name: str
    input_gain: Annotated[int, Field(ge=0)]
    input_line: Annotated[int, Field(ge=0)]
    led_roles: Annotated[
        list[LedRoleStatus],
        Field(description="The effective role of every board LED, in descriptor order."),
    ]
    ssid: str
    target_host: str
    target_port: Annotated[int, Field(ge=0)]
    transport: TransportStatus


class FactoryResetResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    rebooting: bool
    setup_network: SetupNetworkResponse


class HealthCheck(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    detail: Annotated[str, Field(description="Plain-language description of what the check found.")]
    fixable: Annotated[
        bool, Field(description="Whether the console offers an action that resolves it.")
    ]
    id: Annotated[
        str,
        Field(
            description='Stable machine id, e.g. `"codec"`. Scripts and the console key off this.'
        ),
    ]
    remedy: Annotated[
        str | None, Field(description="What the user does about it, when there is something to do.")
    ] = None
    severity: Severity
    status: CheckStatus


class HealthReport(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    checks: list[HealthCheck]
    status: Severity


class Led(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_low: Annotated[
        bool | None, Field(description="`true` when driving the GPIO low lights the LED.")
    ] = None
    default_role: Annotated[
        LedRole | None,
        Field(
            description="Role applied until the user assigns another, so a board author can wire a\nstatus light while leaving decorative LEDs dark."
        ),
    ] = None
    gpio: Annotated[int, Field(ge=0)]
    id: Annotated[
        str,
        Field(
            description="Stable id, unique within the board, used to address the LED in settings."
        ),
    ]
    label: Annotated[str, Field(description="Human-readable name the console shows for this LED.")]


class LedCapabilityStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    active_low: bool
    default_role: LedRole
    gpio: Annotated[int, Field(ge=0)]
    id: str
    label: str


class Board(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_atten_max_db: Annotated[
        int, Field(description="Upper bound of the ADC attenuation control, in dB.", ge=0)
    ]
    analog_passthrough: AnalogPassthroughCapability | None = None
    buttons: Annotated[
        list[Button] | None,
        Field(
            description="Board buttons the user can assign actions to, in console order. Empty\nwhen the board wires none."
        ),
    ] = None
    codec: Annotated[
        CodecSpec,
        Field(description="Codec driver and bus address needed to control line-in capture."),
    ]
    id: Annotated[
        str,
        Field(
            description="Stable descriptor id. Official presets and custom boards share this\nidentity shape."
        ),
    ]
    input_gain_max: Annotated[
        int,
        Field(description="Upper bound of the input gain control, as a 0..=100 percentage.", ge=0),
    ]
    input_lines: Annotated[
        list[InputOption],
        Field(
            description="Selectable inputs in console order, never empty; the first entry is\nthe factory default."
        ),
    ]
    leds: Annotated[
        list[Led] | None,
        Field(
            description="Board LEDs the user can assign roles to, in console order. Empty when the\nboard wires none."
        ),
    ] = None
    name: Annotated[
        str, Field(description="Human-readable board name, advertised in `/api/status`.")
    ]
    pins: Annotated[
        PinMap, Field(description="ESP32 GPIO wiring for codec control and I2S capture.")
    ]


class CapabilitiesStatus(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    adc_atten_max_db: Annotated[int, Field(ge=0)]
    analog_passthrough: AnalogPassthroughCapabilityStatus | None = None
    board: str
    board_id: str
    buttons: list[ButtonCapabilityStatus]
    codec: CodecStatus
    input_gain_max: Annotated[int, Field(ge=0)]
    input_lines: list[InputLineStatus]
    leds: list[LedCapabilityStatus]
    pins: PinMapStatus


class StatusResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    analog_passthrough: AnalogPassthroughStatus
    audio: AudioStatus
    auth_required: bool
    capabilities: CapabilitiesStatus
    config_source: str
    configuration_writable: bool
    device_name: str
    diagnostics: DiagnosticsStatus
    firmware_version: str
    health: HealthReport
    indicator: IndicatorStatus
    metrics: MetricsStatus
    mode: str
    ota: OtaStatus
    stream: StreamControlStatus
    system: SystemStatus
    target: TargetStatus
    web_server: bool
    wifi: WifiStatus


class BoardCatalogResponse(BaseModel):
    model_config = ConfigDict(
        extra="ignore",
    )
    boards: list[CapabilitiesStatus]
    selected_board: CapabilitiesStatus
    selected_board_id: str
