version: 2

multi-ecosystem-groups:
  integration:
    commit-message:
      prefix: build(deps)
    schedule:
      interval: weekly

updates:
  - package-ecosystem: uv
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: integration

  - package-ecosystem: docker
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: integration

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci(deps)
    schedule:
      interval: weekly
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
