# GitHub Release bodies are the changelog HACS presents to users.

[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}\
- {{ commit.message | split(pat="\n") | first | upper_first | trim }}
{% endfor %}\
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
split_commits = false
protect_breaking_commits = true
tag_pattern = "v[0-9]*"
topo_order = false
sort_commits = "newest"
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Fixes" },
  { message = "^perf", group = "<!-- 2 -->Performance" },
  { message = "^refactor", skip = true },
  { message = "^docs", skip = true },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
  { message = "^test", skip = true },
  { message = "^build", skip = true },
  { message = "^style", skip = true },
  { message = ".*", skip = true },
]
